name: '_COSMO Alpaca - Sync Secrets'

on:
  workflow_call:
    inputs:
      backendUrl:
        description: COSMO Alpaca backend URL
        required: true
        type: string
      additionalSecrets:
        description: Comma-separated list of additional secret names to always include
        required: false
        type: string
        default: 'GitHubPackagesContext,licenseFileUrl'
      mode:
        description: GetAndUpdate searches AL-Go settings files and backend, Update only queries backend
        required: false
        type: string
        default: 'GetAndUpdate'

defaults:
  run:
    shell: pwsh

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}
  ALPACA_BACKEND_URL: ${{ inputs.backendUrl }}
  # Settings must contain at least one property for ReadSecrets to function correctly.
  Settings: '{"placeholder": "value"}'

jobs:
  SyncAlpacaSecrets:
    name: Sync COSMO Alpaca Secrets
    runs-on: [ ubuntu-latest ]
    steps:

      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Get secrets for sync
        id: GetSecretsForSync
        uses: cosmoconsult/Alpaca-Actions/Actions/GetSecretsForSync@v2.4.0
        with:
          shell: pwsh
          token: ${{ secrets.GITHUB_TOKEN }}
          mode: ${{ inputs.mode }}
          additionalSecrets: ${{ inputs.additionalSecrets }}
      
      - name: Read secrets
        id: ReadSecrets
        uses: microsoft/AL-Go-Actions/ReadSecrets@v8.0
        with:
          shell: pwsh
          gitHubSecrets: ${{ toJson(secrets) }}
          getSecrets: '${{ steps.GetSecretsForSync.outputs.secretsForSync }}'
      
      - id: SyncSecrets
        name: Sync Secrets
        uses: cosmoconsult/Alpaca-Actions/Actions/SyncSecrets@v2.4.0
        with:
          shell: pwsh
          token: ${{ secrets.GITHUB_TOKEN }}
          secretsJson: ${{ steps.ReadSecrets.outputs.Secrets }}
