name: '_COSMO Alpaca - Sync Secrets'

on:
  workflow_call:
    inputs:
      backendUrl:
        description: COSMO Alpaca backend Url
        required: true
        type: string
      secrets:
        description: A comma separated list of secrets to sync
        required: false
        type: string
        default: 'GhTokenWorkflow,NuGetContext,GitHubPackagesContext,appDependencySecrets'

defaults:
  run:
    shell: pwsh

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}
  ALPACA_BACKEND_URL: ${{ inputs.backendUrl }}

jobs:
  SyncAlpacaSecrets:
    name: Sync COSMO Alpaca Secrets
    runs-on: [ ubuntu-latest ]
    steps:

      - name: Read settings
        uses: microsoft/AL-Go-Actions/ReadSettings@v8.0
        with:
          shell: pwsh
          get: templateUrl
      
      - name: Read secrets
        id: ReadSecrets
        uses: microsoft/AL-Go-Actions/ReadSecrets@v8.0
        with:
          shell: pwsh
          gitHubSecrets: ${{ toJson(secrets) }}
          getSecrets: '${{ inputs.secrets }}'
      
      - id: SyncSecrets
        name: Sync Secrets
        uses: cosmoconsult/Alpaca-Actions/Actions/SyncSecrets@v2.3.1
        with:
          shell: pwsh
          token: ${{ secrets.GITHUB_TOKEN }}
          secretsJson: ${{ steps.ReadSecrets.outputs.Secrets }}
