name: '[DEPRECATED]_COSMO Alpaca - Sync Secrets'

on:
  workflow_call:

jobs:
  Deprecated:
    name: This workflow is deprecated
    runs-on: ubuntu-latest
    steps:
      - run: echo "::error::This workflow is deprecated and only exists for automatic removal in target repositories on update AL-Go system files. Please use the '_AlpacaSyncConfigs.yaml' workflow instead."
